name: Feature request
description: Suggest an idea for Flang
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: What are you trying to do that Flang doesn't support today?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to happen?
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Mockups, links, or examples from other apps
    validations:
      required: false
